-- MySQL Script generated by MySQL Workbench
-- Wed Dec 26 22:35:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`places` (
  `idplaces` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idplaces`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hotels` (
  `idhotels` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(5000) NULL,
  `link` VARCHAR(200) NULL,
  `places_idplaces` INT NOT NULL,
  PRIMARY KEY (`idhotels`, `places_idplaces`),
  INDEX `fk_hotels_places_idx` (`places_idplaces` ASC),
  CONSTRAINT `fk_hotels_places`
    FOREIGN KEY (`places_idplaces`)
    REFERENCES `mydb`.`places` (`idplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurants` (
  `idrestaurants` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(5000) NULL,
  `link` VARCHAR(200) NULL,
  `places_idplaces` INT NOT NULL,
  PRIMARY KEY (`idrestaurants`, `places_idplaces`),
  INDEX `fk_restaurants_places1_idx` (`places_idplaces` ASC),
  CONSTRAINT `fk_restaurants_places1`
    FOREIGN KEY (`places_idplaces`)
    REFERENCES `mydb`.`places` (`idplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attractions` (
  `idattractions` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(5000) NULL,
  `link` VARCHAR(200) NULL,
  `places_idplaces` INT NOT NULL,
  PRIMARY KEY (`idattractions`, `places_idplaces`),
  INDEX `fk_attractions_places1_idx` (`places_idplaces` ASC),
  CONSTRAINT `fk_attractions_places1`
    FOREIGN KEY (`places_idplaces`)
    REFERENCES `mydb`.`places` (`idplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_places` (
  `users_idusers` INT NOT NULL,
  `places_idplaces` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `places_idplaces`),
  INDEX `fk_users_has_places_places1_idx` (`places_idplaces` ASC),
  INDEX `fk_users_has_places_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_users_has_places_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_places_places1`
    FOREIGN KEY (`places_idplaces`)
    REFERENCES `mydb`.`places` (`idplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_attractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_attractions` (
  `users_idusers` INT NOT NULL,
  `attractions_idattractions` INT NOT NULL,
  `attractions_places_idplaces` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `attractions_idattractions`, `attractions_places_idplaces`),
  INDEX `fk_users_has_attractions_attractions1_idx` (`attractions_idattractions` ASC, `attractions_places_idplaces` ASC),
  INDEX `fk_users_has_attractions_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_users_has_attractions_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_attractions_attractions1`
    FOREIGN KEY (`attractions_idattractions` , `attractions_places_idplaces`)
    REFERENCES `mydb`.`attractions` (`idattractions` , `places_idplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_hotels` (
  `users_idusers` INT NOT NULL,
  `hotels_idhotels` INT NOT NULL,
  `hotels_places_idplaces` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `hotels_idhotels`, `hotels_places_idplaces`),
  INDEX `fk_users_has_hotels_hotels1_idx` (`hotels_idhotels` ASC, `hotels_places_idplaces` ASC),
  INDEX `fk_users_has_hotels_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_users_has_hotels_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_hotels_hotels1`
    FOREIGN KEY (`hotels_idhotels` , `hotels_places_idplaces`)
    REFERENCES `mydb`.`hotels` (`idhotels` , `places_idplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_restaurants` (
  `users_idusers` INT NOT NULL,
  `restaurants_idrestaurants` INT NOT NULL,
  `restaurants_places_idplaces` INT NOT NULL,
  PRIMARY KEY (`users_idusers`, `restaurants_idrestaurants`, `restaurants_places_idplaces`),
  INDEX `fk_users_has_restaurants_restaurants1_idx` (`restaurants_idrestaurants` ASC, `restaurants_places_idplaces` ASC),
  INDEX `fk_users_has_restaurants_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_users_has_restaurants_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_restaurants_restaurants1`
    FOREIGN KEY (`restaurants_idrestaurants` , `restaurants_places_idplaces`)
    REFERENCES `mydb`.`restaurants` (`idrestaurants` , `places_idplaces`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
